# Use this file to define your own rules.

## Install dir

#INSTALLDIR = /usr/local/bin

## Add your flags

#LIBS   += -lpthread
#CFLAGS += -I$(SRCDIR)/includes

## Rules

#ifdef INSTALLDIR
#default: install
#endif
